### PR TITLE
using natural middleware orderdering for dispatching

### PR DESCRIPTION
**Pull request by denyadzi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | 

I feel that reverse ordering leads to cofuse

### CODE REVIEW

**Comment by samdark** [comment]
Note that middleware dispatcher is used in both routes/route groups and application. That would change order in both.

**Comment by samdark** [comment]
@denyadzi how do you see before/after configs?

**Comment by samdark** [comment]
Also, what do you want to achieve by replacing a stack with queue? What's the main motivation for the pull request? What problems should it solve?

**Comment by denyadzi** [comment]
@samdark Stack -> queue change is only about code semantics, to keep it clear. The whole idea is about doing FIFO and stack is wrong data structure for that.

By before/after configs I've understood the process of mixing middlewares in router. Please, could you expand the question if I'm wrong.
I've done some playing with routing and natural ordering seems to be possible for adoption (see [this commit](https://github.com/denyadzi/router/commit/edba0c0eee785f5dd38e13a48a5a7a82ebec5677)).

Eventually middleware-dispatcher is an independent package, so it should be conveniently usable by itself. In my opinion with reverse middleware input it isn't.

**Comment by samdark** [comment]
> By before/after configs I've understood the process of mixing middlewares in router. Please, could you expand the question if I'm wrong.

There are two places in the app that will be affected:

1. https://github.com/yiisoft/yii-demo/blob/master/config/web/application.php#L21
2. https://github.com/yiisoft/yii-demo/blob/master/config/routes.php#L81

**Comment by denyadzi** [comment]
I think i should clear for myself how your example of authentication/permission checking chain works with reverse middleware dispatching, currently it's not obvious for me

**Comment by denyadzi** [comment]
@samdark configuration changes [this way](https://github.com/denyadzi/yii-demo/commit/99bb7896f6bbb6ea1e7f6ae3051c148259afb36f). Blog post edit access checking remains the same, but in this case it works as supposed to -- authentication first, if it failes it goes to login screen else it goes to check editPost permission.

**Comment by samdark** [comment]
Decided to implement it but in a bit different way.

**Comment by samdark** [comment]
Thanks for PR anyway.

**Pull request closed without merging**
